### ISSUE TITLE
Argument resolver doesn't find matching arguments

### ISSUE THREAD

**Issue by elvetemedve** [Behat/Behat#1008]
# The bug
Let's  suppose there are `Api` and `FakeApi` **classes**, where  `FakeApi extends Api`.
And I want Behat to create my context class with these constructor arguments:
```php
class MyContext implements Context
{
    public __construct(Api $api, FakeApi $fakeApi) {}
}
```
In this case the following error will be reported:

>  [Behat\Testwork\Argument\Exception\UnknownParameterValueException]                                                        
>   Can not find a matching value for an argument `$fakeApi` of the method `MyContext::__construct()`.

## Explanation
That happens because `MixedArgumentOrganiser` try to find which parameter to assign by [checking that the parameter is an instance of the argument](https://github.com/Behat/Behat/blob/master/src/Behat/Testwork/Argument/MixedArgumentOrganiser.php#L145-L150). Since both the `Api` instance and `FakeApi` instance are instances of `Api`, argument resolver will associate these parameters with the `$api` argument.

## Workaround
As a possible solution, I removed type hinting to make argument resolver work by argument numbers.

**Comment by everzet** [comment]
Thanks for reporting it.

**Comment by glennmcewan** [comment]
Using the `Symfony2Extension`, the easiest way would be to name the parameters you're passing to the `Context`.

The issue in this case would be an easy* fix, by checking which one has a more direct relationship to each argument (for example, using `get_class` to check if `FakeApi` is equal, where `Api` would fail, or by climbing the inheritance chain to find which service is the closest relative).

\* I say easy, because it then becomes tricky when you have two arguments which ask for the same interface -- implemented by two different classes -- to be injected. How on earth do you know which you want in that scenario? It is also tricky when you have two arguments which request different interfaces, and each service candidate satisfies both interfaces.

I've had a toy around with this and in this case where you're asking for `FakeApi` which is a child of `Api`, it can be solved by adding a new method to `MixedArgumentOrganiser` like `prepareTypehintedArguments` similar to the other methods, and then iterating each argument and matching the best fitting candidate. I'll make a PR as a POC shortly as I've walked in to the same issue as this…

**Comment by glennmcewan** [comment]
@everzet @elvetemedve delay in making the PR due extenuating circumstances, but I have created it here: behat/behat#1028

That should resolve the issue for your case, at least. Before it is merged, it will need unit tests adding in, but I had no luck in getting them successfully on a fresh copy of `master`, so I have left it as it is as a POC, just in case it does not get merged / approved.
