### ISSUE TITLE
Doctrine event listener not called in Behat tests

### ISSUE THREAD

**Issue by paullla** [Behat/Behat#1020]
I am using doctrine event listener 'postLoad' in Symfony3. It works ok on the web, but in Behat tests is not called at all. What could be the problem?

**Comment by Taluu** [comment]
Have you tried the Symfony extension ? Behat does not call Symfony's container...

**Comment by paullla** [comment]
Yes, I'm using symfony extension.

**Comment by Taluu** [comment]
Then report this on the [Symfony extension](https://github.com/Behat/Symfony2Extension). On a side note, you should also provide how you are making the tests (http requests ? directly using the kernel ?), and your feature / contexts files to give more context to your problem.

**Comment by spolischook** [comment]
It looks like you miss something. You need duble check all configurations because it no difference between direct call and behat call. First of all check base_url in behat.yml, it should be the same url as you calling while you notice that listener is calling.
How you recognize that listener not calling?
