### ISSUE TITLE
Behat fails to parse individual scenarios when relative paths are used

### ISSUE THREAD

**Issue by deviantintegral** [Behat/Behat#1043]
If you try to run an individual scenario, it only works if you are running form the root of your project. Otherwise, you can pass a directory or feature file only. If you convert the path to the features to be an absolute path, it works fine. For example:

```
$ ../../vendor/bin/behat -c tests/src/Behat/behat.local.yml $(pwd)/tests/src/Behat/features/testing.feature:3
```

works fine, but if I remove `$(pwd)/` behat fails with:

```
$ ../../vendor/bin/behat -c tests/src/Behat/behat.local.yml tests/src/Behat/features/testing.feature:3
  [Behat\Testwork\Tester\Exception\WrongPathsException]
  No specifications found at path(s) `tests/src/Behat/features/testing.feature:3`.
```

**Comment by spolischook** [comment]
I guess behat try to find your feature from the path of your config. Try:
```bash
bin/behat -c tests/src/Behat/behat.local.yml features/testing.feature:3
```
I suggest use composer bin path, see https://getcomposer.org/doc/articles/vendor-binaries.md

**Comment by deviantintegral** [comment]
That works, but only if I move features up to the root of my project. This is for a Drupal module, where the tests are owned by the module (as there isn't a "site" to test against).

Is there any reason why Behat couldn't convert the relative paths to absolute paths when referencing them internally?

**Comment by spolischook** [comment]
Is this issue same for feature running? or it happens only for scenario run?

**Comment by glennunipro** [comment]
This is a bug which I have found to be caused by the `GherkinExtension` class; it does not give the basePath to each of its loaders, so the loaders are not aware of what the base path is.

This works when you're already in the root, because `is_file` will return true (because the relative path is equal to the absolute path, so it doesn't need to go down the route of looking in the base path).

So, I've created a PR [here](1046) which resolves this, feel free to give it a try and let me know how that works.

**Comment by glennunipro** [comment]
Turns out that in my previous comment, the solution was completely wrong. It did fix the case, when running Behat in this scenario, but it broke the unit tests spectacularly (due to the way the Behat self tests work, writing feature files to a temporary folder, outside of the base path).

The solution instead is to "sanitise" the given path in the FilesystemFeatureLocator, so that it strips out the line ranges from the path before searching for the file in the filesystem.

I've updated my original PR, builds now passing (except one code style recommendation). If you check out that branch into your project, it should resolve your issue @deviantintegral.
