### ISSUE TITLE
Different kinds of environment for Scenario and Scenario Outline: is it correct?

### ISSUE THREAD

**Issue by BR0kEN-** [Behat/Behat#1052]
Is it correct that `@BeforeScenario` gets `Behat\Behat\Context\Environment\UninitializedContextEnvironment` for `Scenario Outline` and `Behat\Behat\Context\Environment\InitializedContextEnvironment` for regular `Scenario`?

It was changed in https://github.com/Behat/Behat/releases/tag/v3.2.0rc1. Before `3.2.x` there was `InitializedContextEnvironment` for all kind of `Scenario`.

**Comment by BR0kEN-** [comment]
Reference: https://github.com/Behat/Behat/pull/911

```
git clone git@github.com:Behat/Behat.git
cd Behat/
git checkout v3.3.1
git rebase -i d9cac87edd73c71c61c185244c44a02ab174c0b8
# Drop 695a37f5b31b708553be6dd6263cef816322b16f
cd ../
rm -rf vendor/behat/behat/
cp -r Behat/ vendor/behat/behat
```

Gets it back to work (doable if `composer.lock` has `v3.3.1`).

**Comment by phenaproxima** [comment]
I am encountering this problem in acquia/lightning. When we switch to Behat 3.3.1, our Scenario Outline tests break because of an UninitializedContextEnvironment being present when we were expecting InitializedContextEnvironment. Is this by design, or is it honestly broken? Is it something Drupal Extension (upon which we are relying) should work around? Any advice would be helpful here.

**Comment by phenaproxima** [comment]
Turns out the problem I was having was fixable in Drupal Extension: jhedstrom/drupalextension#390

**Comment by BR0kEN-** [comment]
Thanks for pointing out, @phenaproxima. I got it fixed too.
