### ISSUE TITLE
Feature Request:  Chaining behat config files

### ISSUE THREAD

**Issue by lhridley** [Behat/Behat#1058]
I have a use case for chaining behat config files, allowing values set in subsequent files to either supplement override those values from previous files, similar to the way you can chain docker config files:

[pathtobinary]/behat -c [pathtofile]/behat.yml [pathtofile]/behat-stg.yml [parameters]

The use case is a staging server (with multiple sites) set up to execute a test suite on a staging site after a branch is deployed to the staging server.

(1) The base behat.yml file is designed to execute a test suite on a CI server (Travis CI).
(2) The behat-stg.yml file would contain differences between the testing environments for a particular project
(3)  The tests executed on the staging server would use the "chained" config files

Environment variables won't work here because there are multiple sites staged on this server, and there are two test servers involved.

Right now I am maintaining two behat.yml files with differences between the two.  The behat.yml files are getting quite large, with a number of test suites configured in each, using customized contexts and parameters passed in from the behat.yml file.  This is cumbersome and subject to human error since the behat.yml file is revised regularly as tests are added to the suite.

**Comment by bwowk** [comment]
There's the `imports` key on behat.yml as you can find [here](http://docs.behat.org/en/v2.5/guides/7.config.html#imports) (For some reason there's no mention of it on the latest docs, but it still works). That way you can import extra configs on your alternate environment, and those will be merged (looks like suites section is purposefully overwritten instead of merged)

Another option would be to have different profiles, [overriding just the parts you need](https://gist.github.com/bowsersenior/979804)
