### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by respinoza** [Behat/Behat#1108]
Hello,

We upgraded behat and it pulled some 4.0 symfony components and we get the following error

```php
In RemoveUnusedDefinitionsPass.php line 76:
                                             
  [Exception]                                
  Serialization of 'Closure' is not allowed  
                                             

Exception trace:
 serialize() at /web/vendor/symfony/dependency-injection/Compiler/RemoveUnusedDefinitionsPass.php:76
 Symfony\Component\DependencyInjection\Compiler\RemoveUnusedDefinitionsPass->process() at /web/vendor/symfony/dependen
cy-injection/Compiler/RepeatedPass.php:57
 Symfony\Component\DependencyInjection\Compiler\RepeatedPass->process() at /web/vendor/symfony/dependency-injection/Co
mpiler/Compiler.php:95
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /web/vendor/symfony/dependency-injection/Contai
nerBuilder.php:699
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /web/vendor/behat/behat/src/Behat/Testwork/Cli/A
pplication.php:187
 Behat\Testwork\Cli\Application->createContainer() at /web/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php:1
61
 Behat\Testwork\Cli\Application->createCommand() at /web/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php:122
 Behat\Testwork\Cli\Application->doRun() at /web/vendor/symfony/console/Application.php:129
 Symfony\Component\Console\Application->run() at /web/vendor/behat/behat/bin/behat:34
```

If we force to use symfony dependency injection to be ^3.0, everything works as normal (tested with 3.4)

**Comment by t1k3hu** [comment]
`"symfony/dependency-injection": "3.3.13"`

**Comment by valorin** [comment]
Looks like this was introduced here: https://github.com/Behat/Behat/issues/1108

**Comment by drbyte** [comment]
Experiencing the same problem here.

**Comment by drbyte** [comment]
Had to manually add a `dev` dependency for `symfony/dependency-injection:"3.*"` in my `composer.json`:

`composer require --dev symfony/dependency-injection:"3.*"`
and then 
`composer update`

Not a fan of having to force this. 
Been fence-sitting about converting all my tests to something other than behat. This may be the shove I needed to go and do it. Sigh.

**Comment by philtweir** [comment]
Working with Laravel 5.6, I am unable to roll back symfony/odependency-injection and cannot see another work-around here - apologies if I am missing another Issue/PR, as it seems quiet on this one since Dec. However, I _think_ the change referenced [above](https://github.com/flaxandteal/Behat/commit/8f9c9d9a4dc857bc3d7437bd4ea27d3e2b2297d7) fixes this by providing the service container as a Symfony Reference rather than an object.

I am unfamiliar with Symfony DI, so have had to get to grips with the basics to get this far - as such, I would appreciate some feedback please in case this looks likely to break something non-obvious, or if it's even a sane approach, or misses the point of that class, before tidying up for a PR.

Side-note: I am using this with behat-laravel-extension, which needs a similar tweak to work, but with that, I now have working Behat 3.4.3 with symfony/dependency-injection 4.1.1

**Comment by stof** [comment]
@philtweir your change looks legitimate. Please open a PR for it.

**Comment by philtweir** [comment]
Many thanks, PR is open at #1163

**Comment by jcornide** [comment]
Hi, +1 with this problem, would be great if this get solved
