### ISSUE TITLE
BeforeHook Exceptions are not dumped to JUnit

### ISSUE THREAD

**Issue by oleg-andreyev** [Behat/Behat#1195]
If I have an exception somewhere in `before*` events, it will not be dumped into a file.
Hooks stats are collection into `\Behat\Behat\Output\Statistics\TotalStatistics::$failedHookStats` but `\Behat\Behat\Output\Node\EventListener\JUnit\JUnitFeatureElementListener::printFeatureOnAfterEvent` does not iterate over it.

**Comment by carlos-granados** [comment]
The XSD can be found here https://github.com/Behat/Behat/tree/master/features/bootstrap/schema

**Comment by acoulton** [comment]
@carlos-granados sorry for the slow reply.

I think I've understood right that we have one JUnit XML per suite, so like this?

* Behat suite => `testsuites` root node
* Behat feature => `testsuite`

I find it slightly hard to give an opinion without knowing how the junit would be parsed / rendered by a tool - I used Jenkins & JUnit in the past but haven't done for quite a long time.

My recollection though is that although our XSD types the `errors` etc attributes as "string", the common usage is that they are a number e.g. `<testsuite name="some feature" tests="8" failures="0" errors="5">` where the number is the number of failed / errored tests (not the number of failures / errors, which may be higher). I'm not sure if clients expect that the `errors` number on a `<testsuites>` will always be the total of the numbers on the `<testsuite>` children.

There's documentation here that seems recent and matches what I roughly remember -  https://github.com/testmoapp/junitxml?tab=readme-ov-file#complete-junit-xml-example - I haven't really checked the source of that, just googled it...

I think:

- For step / scenario hooks it would probably be more correct to use the `<error>` than  `<failure>` node - but if we're already using `<failure>` for step then it is probably better to be consistent.
- For feature hooks, `<system-err>` is probably the right place for the output, but I guess clients might just treat that as informational / debug (it's officially any stderr output during the test) - so we would probably need to also increment one of the failures / errors attributes to have a tool recognise a failed run..
- For suite hooks, I agree there's not really a logical place. Best idea I have is to just put it in the first `<testsuite>` - which at least correctly reflects when it happened?

**Comment by carlos-granados** [comment]
Thanks @acoulton that more or less matches what I had in mind. Let me work on trying to implement this as best as possible

**Comment by acoulton** [comment]
Actually, another thought (sorry, still drinking my coffee :laughing:).

Maybe it makes sense if if feature *and* suite hooks are reported as `<error>` in the first (for beforeXXX) or last (for afterXXX) `<testsuite>` they affect, incrementing the errors count on the parent nodes accordingly. I know from our side they're not really part of the scenario, but that logically reflects the execution sequence and it is probably the safest way to make sure a JUnit client recognises / understands / displays them in a way that is clear to users?

It looks like at the moment if a beforeFeature / beforeSuite hook fails we record the tests as `skipped` in JUnit. Maybe it would be more logical to record them as `errored` to show that we tried to run them, but were prevented by an error (rather than e.g. the test being skipped for some expected reason).

Don't know how hard that would be to implement though - and might be worth looking at how ant / JUnit / other JUnit-based tools handle cases like this, we can't be the only tool that supports some kind of pre / post hook?
