### ISSUE TITLE
Using PHPUnit expectations in @Then step?

### ISSUE THREAD

**Issue by paddelboot** [Behat/Behat#1207]
There are examples in the Behat documentation that show how to use PHPUnit assertions in the @Then step. What if I don't expect some object property to be set, but instead, a method being called, like `sendEmail()`?

What I tried:

    /**
     * @Then an offer to download the ebook must be sent via email
     */
    public function anOfferToDownloadEbookMustBeSentViaEmail( $arg1 ) {

        $this->Lead->expects( TestCase::once() )->method( 'send' )->with( TestCase::equalTo( 'ebook' ) );

        $this->Lead->isEligibleForNextDigitalProduct();
    }

But even though `send` is never called in my `Lead::isEligibleForNextDigitalProduct` method, the test passes. If I do some nonsense assertion like 1 equals 2, I do get the expected error message. Did I misunderstand something?

**Comment by stof** [comment]
Well, I think you are missing the call checking the expectation on the mock object in your case (something you don't see when using mocks inside PHPUnit because PHPUnit does it for you already).
The exception would happen inside `$mockObject->__phpunit_verify()` and you don't call it (see the private `TestCase::verifyMockObjects` method to see the implementation in PHPUnit)

**Comment by paddelboot** [comment]
Thanks for the hint. Does it maybe make more sense to use something like Mailtrap - because all I do here is to check that a method was called, but the behaviour I really want to test via BDD/Behat is whether an email is sent.
