### ISSUE TITLE
Unhelpful exception message when --format=junit is used without specifying --out

### ISSUE THREAD

**Issue by dkarlovi** [Behat/Behat#1408]
```
 ̇$ vendor/bin/behat --format=junit

Deprecated: is_file(): Passing null to parameter #1 ($filename) of type string is deprecated in /app/vendor/behat/behat/src/Behat/Testwork/Output/Printer/Factory/FilesystemOutputFactory.php on line 47

Deprecated: is_dir(): Passing null to parameter #1 ($filename) of type string is deprecated in /app/vendor/behat/behat/src/Behat/Testwork/Output/Printer/Factory/FilesystemOutputFactory.php on line 52

Deprecated: mkdir(): Passing null to parameter #1 ($directory) of type string is deprecated in /app/vendor/behat/behat/src/Behat/Testwork/Output/Printer/Factory/FilesystemOutputFactory.php on line 53

Warning: mkdir(): Invalid path in /app/vendor/behat/behat/src/Behat/Testwork/Output/Printer/Factory/FilesystemOutputFactory.php on line 53

Warning: fopen(/file.xml): Failed to open stream: Permission denied in /app/vendor/behat/behat/src/Behat/Testwork/Output/Printer/Factory/FilesystemOutputFactory.php on line 63

                                                                
  The StreamOutput class needs a stream as its first argument.  
  ```
  
  It requires you to also pass `--out`, but that's not clear from the error message at all.

Options from discussion in Symfony Slack:
1. default to CWD
2. clear exception that `--out` is now required

**Comment by dkarlovi** [comment]
@carlos-granados this is IMO a bug, not a feature suggestion.

**Comment by acoulton** [comment]
@carlos-granados @dkarlovi I have reproduced this and agree it's a bug as far as the exception message is very unclear (and in my configuration, a lot more verbose than the example in the issue description - I got multiple pages of stack trace in the console for each of the Deprecated / Warning lines before the final `The StreamOutput class needs a stream as its first argument`.

I have renamed the issue, as I think the fix is just to make the failure message clear e.g. `You must specify --out as the path to write your junit file` (or similar).

Giving the formatter a default would be a feature request - and I'm not convinced defaulting to CWD is a good idea, I don't think we should be writing to arbitrary filesystem locations without the user explicitly configuring that.
