### ISSUE TITLE
Adding validaton for data in PyString.

### ISSUE THREAD

**Issue by lasotaartur** [Behat/Behat#1432]
Does it possible to add validation for a data in PyString format in behat step? 
For example when some records are prepared for scenario (given) then, it will be worth validating that some fields are required in PyString for this behat step.

**Comment by stof** [comment]
there is no builtin way to do that. You need to do it inside the implementation of your step.

**Comment by lasotaartur** [comment]
Yes, I know, but it could be good feature in behat.

**Comment by uuf6429** [comment]
@lasotaartur that's unlikely to happen since it is very, _very_, specific to your individual use-case.

Even the implementation is very specific and subjective:
- is it about some simple validation ("value required", "must be numeric"..) or more complex ("must be between X and Y", "must match an IP address"..)
- in either case, it probably makes sense to use an external library for validation
- how would you trigger/define the validation?
  - by an external schema? attached with a gherkin attribute?
  - by matching the table header name with a list (columnName => validations) list configured somewhere?
  - in case of simple validation, by special formatting on the column name? (e.g. `name*` =  value required, `xx id` = must be a number...)
- it's very unlikely that a lot of people would actually use this feature
- the very simple approach, as stof mentioned, is to do it in your step definitions (which isn't something that behat does automatically for you anyway)

**Comment by acoulton** [comment]
As @uuf6429 I can't see a way this could be implemented generically in behat to suit everyone. For a start, in our projects we have some PyString that are JSON, some YAML, some XML...

The easiest solution is to validate the content of the string in your step implementation, where you know exactly what you're expecting.
