### ISSUE TITLE
Progress vs pretty output -- Progress is WAY slower!

### ISSUE THREAD

**Issue by jnicola** [Behat/Behat#1469]
Testing everything out on a jenkins job we've got called "test-a-branch" for letting devs just fire off behat testing. Wanted to try and switch from "pretty" to "progress" output. Unfortunately...

Regular took 59m29.57s (322.09Mb)
Progress took 83m24.01s (322.04Mb)

Why in the world would progress be slower, and that much slower for the matter?

**Comment by mhsdesign** [comment]
I tested your thesis but cannot confirm this with my test suite ... well its also a lot faster but still :D

progress 1:
```
460 scenarios (460 passed)
12432 steps (12432 passed)
0m31.15s (151.45Mb)
```

progress 2:
```
460 scenarios (460 passed)
12432 steps (12432 passed)
0m29.88s (148.31Mb)
```

pretty:
```
460 scenarios (460 passed)
12432 steps (12432 passed)
0m30.27s (148.34Mb)
```

**Comment by jnicola** [comment]
No idea why but for us it's notably slower!

I'm more curious how you're getting 460 scenarios to pass in 30s though!

**Comment by mhsdesign** [comment]
Just a few tests for an event-sourced-content repository called Neos :D

https://github.com/neos/neos-development-collection/tree/9.0/Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features

I didnt write them but they're great and apparently not so slow :D

**Comment by jnicola** [comment]
Ah gotcha. We're using Drupal. Notably slower. Trying to add parallelization and that's proving challenging since each step creates a user etc etc. Quickly overwhelms SQL and times out.

**Comment by stof** [comment]
@jnicola do you have repeated runs in both configurations ? If this was a single run, maybe the CI server was busier at that time.

**Comment by jnicola** [comment]
I haven't put much thought into it in a while as I lost the argument on
progress over the timing issue, and with my coworkers and once they get
their mind set, that's it.

**Comment by acoulton** [comment]
We've used both pretty and progress over the years and I've never seen this. If anything progress is usually slightly faster - potentially partly just due to the reduced volume of output streaming to whatever resource the CI is using to capture it.

I'd also wondered if it was a one-off contention/external issue.

The other possibility might be progress running just *faster* enough that the system under test is getting slightly higher request volume and tipping over into a database/CPU throttling/or similar bottleneck which is slowing things down.

Either way if you've not seen this recently and there are no other reports I think this is unlikely a behat issue so I'll close this for now.
