### ISSUE TITLE
Add ttomdewit as maintainer

### ISSUE THREAD

**Issue by ciaranmcnulty** [Behat/Behat#1494]
It's great we have more maintainers now; 

I'd had a few chats already with @ttomdewit who I know personally about him helping out more with Behat

I'd like to add him to the team if there is no objection? (@acoulton @carlos-granados)

I don't have any more people up my sleeve currently :)

**Comment by carlos-granados** [comment]
@ciaranmcnulty OK with me, but please check with @everzet as he said he preferred to start out with 2 maintainers.But if he is OK, then great to have @ttomdewit as maintainer

**Comment by ttomdewit** [comment]
> @ciaranmcnulty OK with me, but please check with @everzet as he said he preferred to start out with 2 maintainers.But if he is OK, then great to have @ttomdewit as maintainer

I’m happy either way. Fine being on hold a little while, also equally happy to get my hands dirty now the new job is settling in. As long as you all are happy and adding a third isn’t making things too complex!

**Comment by acoulton** [comment]
@ciaranmcnulty likewise very happy to share the load with @ttomdewit, thank you! I don't think it makes things more complex, and even if @everzet thinks it's worth letting things settle a bit it would definitely be an advantage to have @ttomdewit's thoughts as Carlos and I start to work out processes etc.

**Comment by ttomdewit** [comment]
> @ttomdewit sent you an invite. @ciaranmcnulty vouching means a lot

That means the world to me. I will do my best! Thanks for the vote of confidence.

**Comment by carlos-granados** [comment]
@ttomdewit welcome to the team!!

**Comment by ttomdewit** [comment]
> @ttomdewit welcome to the team!!

Thank you! Please feel free to assign me some basic tasks at your discretion!

**Comment by acoulton** [comment]
Thanks @everzet and welcome @ttomdewit look forward to working with you!

**Comment by ttomdewit** [comment]
> Thanks @everzet and welcome @ttomdewit look forward to working with you!

Thank you so very kindly. Also looking forward to working alongside you!

**Comment by ttomdewit** [comment]
@ciaranmcnulty @acoulton @carlos-granados @everzet 

Hey team, hope you are all well.

I’ve been postponing and dreading writing this message for a while already but it’s finally time. I’m not doing too well and can’t currently focus on more than just work for my employer. Once done I have very little energy left to do OSS at the moment. You must’ve already noticed my lack of any serious contribution and I think I took too big of a bite when you accepted me as maintainer in the time I also started my new job.

My hope is that I’ll feel better and more energised soon so I can help out in small steps.

I totally accept if this means I’m losing the maintainer role, temporarily or otherwise, and I leave that to your discretion.

For now, please also accept this as an apology, although I know you’ll say that apologies are not necessary. Sorry for letting you down, I myself had very high hopes of helping the project forward and am ashamed I couldn’t deliver.

Please keep kicking ass, from the sidelines I’ve seen you do amazing work already in such short time.

Hope to catch you soon,

Tom

**Comment by carlos-granados** [comment]
Hey @ttomdewit that's perfectly fine. We all have a lot on our plates and it is ok if you can't handle any additional load for now. So take things slowly and help in any way you can. If after some time you feel that you can't really contribute any longer please let us know.

**Comment by acoulton** [comment]
@ttomdewit there's absolutely no need to apologise or be ashamed, I'm sure we've all been there (I know I have, more than once). Everyone can only do what they can, actual work and the rest of life should always take priority over OSS contributions. You don't owe anyone anything.

If you'd like to stay a maintainer for now and join in whenever you feel like it, that's totally fine. We won't assign or tag you on anything, but feel free to share your thoughts any time.

If you'd prefer to come off the team to avoid getting notification floods etc and rejoin us later that would also be fine. Just let me know and we can update your permissions.

**Comment by ttomdewit** [comment]
@acoulton @carlos-granados Thank you both for the lovely messages, they're greatly appreciated! <3 When I have a little bit more energy I will try and do some simple, small-ish tasks that are "easy starters". Terminator voice: I'll be back.
