### ISSUE TITLE
Output the name of the corresponding step, scenario, feature or suite when a failure on a hook is recorded

### ISSUE THREAD

**Issue by carlos-granados** [Behat/Behat#1495]
When using the --progress formatter there may be was a situation where a test failed in an `after` or `before` hook. The information printed to the output may not be enough to diagnose the issue because we are just told which hook function failed but not the related step, scenario, feature or suite.

When printing out the failed hooks, we should print:
- For `beforeStep` or `afterStep` hooks, the name of the step where the failure happened
- For `beforeScenario` or `afterScenario` hooks, the name of the scenario where the failure happened
- For `beforeFeature` or `afterFeature` hooks, the name of the feature where the failure happened
- For `beforeSuite` or `afterSuite` hooks, the name of the suite where the failure happened

Related to https://github.com/Behat/Behat/pull/1392 and https://github.com/Behat/Behat/issues/842

**Comment by acoulton** [comment]
My only thought is for the step-level hooks it would still help to have more context than just the step, since the same step will probably be used in multiple places and the hook failure could well relate to specific scenarios / features.

It might be enough to give just `path/to/feature.feature:23` in all cases, similar to how the file & line get rendered for failures at the end of the progress printer?

**Comment by carlos-granados** [comment]
Ah, yes that might be the best option
