### ISSUE TITLE
Allow altering the execution order of hooks

### ISSUE THREAD

**Issue by mrtorrent** [Behat/Behat#62]
Currently, as far as I can tell, there is no way to specify where in the stack a hook should be inserted, and they are fired on a first-in, first-out basis. It would be helpful to be able to rearrange the order of hooks for events from within a context.

Sample use case:
1. A feature suite uses Mink to do headless testing on a Symfony application
2. A beforeScenario hook does some set-up on an in-memory database
3. The hook injects the database connection into the service container of the kernel under test (otherwise the kernel would open its own connection, which would effectively be a new database)
4. The hook is queued to run after Mink's `prepareMinkSessions` hook, so that the database connection can be injected after the session is initialised. Otherwise, Mink resets the session after our database set-up hook and the service container and its database connection are lost.

**Comment by pfrenssen** [comment]
Let's reopen this feature request. It made sense back in 2011 for projects to have only a `FeatureContext` file that contains all the code and it was possible to determine the hook order by rearranging them in the file, but this is no longer the case today.

Nowadays projects are composed of dozens of contexts from various sources. It would be useful to be able to set an optional priority for certain hooks so that we can determine their execution order, especially in the case where some code needs to run before or after a hook supplied by a third party context.

@everzet @ciaranmcnulty

**Comment by miiimooo** [comment]
I think I'm also facing an issue related to this in my teardown when adding check for whether entities are still referenced by other entities. There it's necessary to know in which order cleanup code is running.
I wonder are hooks ordered in the same order as the `context` key in behat.yml ?

**Comment by stof** [comment]
@miiimooo it seems like they are, as they are loaded by iterating over contexts

**Comment by gaelg** [comment]
Thanks. Changing the context order in behat.yml helped in my use case.
