### ISSUE TITLE
Turnip custom step placeholders

### ISSUE THREAD

**Issue by mloureiro** [Behat/Behat#627]
Hi

Not sure if [custom step placeholders](https://github.com/jnicklas/turnip/#custom-step-placeholders) are implemented yet, couldn't find any mention of it (doc's or code).

Is it possible? (or will it be?)

Thanks

**Comment by cawolf** [comment]
Hi all,

I'm really sorry to resurrect this, but I'm currently maintaining a growing set of contexts and step definitions, and whenever I need to expand an actor, e.g. `(?:|I|you|A user)` to `(?:|I|you|A user|Another actor)`, I have to search and replace over multiple distributed files instead of just changing one central `const`.

I know that using regular expressions like this bear the risk of ambigous step definitions, but adding a feature to easily maintain these expressions leaves that risk untouched. Besides, Behat will tell me whenever it couldn't identify a single step definition to go to, so it would be safe anyways.

I was thinking about some kind of preprocessors for these regexes to get this done. What do you think about adding this feature?

Best regards,
@cwolf
