### ISSUE TITLE
Impossible to modify scenarios in beforeFeature event

### ISSUE THREAD

**Issue by marmotz** [Behat/Behat#67]
In a FeatureContext, if I create a "@beforeFeature" static method, i can't modify scenarios (add tag(s), by example) because in behat/src/Behat/Behat/Tester/FeatureTester.php file, scenarios was already get in a variable (line 75) and use later (line 80).

I think, you should do something like that:

```
if (count($feature->getScenarios())) {
    $this->dispatcher->dispatch(
        'beforeFeature', new FeatureEvent($feature, $this->parameters)
    );

    foreach ($feature->getScenarios() as $scenario) {
        ...
    }
}
```

**Comment by cpintea** [comment]
Any news on the problem of adding a new scenario grammatically? What i want is to rerun the failed scenarios bunt in the same behat run in which they fail. Because in a significant number of time there are spurious failure (cause by network , cloud infrastructure) i need to rerun test in case of failure several time from code, handle the results and generate one report(with spurious fail information). One solution could be to re-inject failed scenarios in behate run (after feature maybe). or an intermediary hook in which you can add grammatically scenarios node that fail (object previous saved ). There is any solution to do this beside of do a framework to handle several behat runs save intermediary results and compile after you run a behat --rerun

**Comment by jakzal** [comment]
@cpintea this issue was closed as it's not a practice a testing framework should promote.

Automated tests should be repeatable. It should be possible to run them many times in a row and get exactly the same results. Otherwise there's no trust in the test suite and in extreme cases maintaining such test suite stops being beneficial. 

In my experience, instead of trying to work around fragile tests I found it better to make them less fragile. This might require changing your testing strategy or appllication design.

Btw, I don't encourage it, but a simple way to solve your problem (if I understood it correctly) is to try a to rerun failed tests a few times:

```bash
 n=0; until [ $n -ge 5 ]
 do
      ./vendor/bin/behat --rerun && break
      n=$[$n+1]
 done
```

You'd have to merge results in some way though.

**Comment by oleg-andreyev** [comment]
This could be useful, when you have quite large set (~4K) of e2e scenarios and run them in **parallel**, and to guarantee uniqueness for commons steps, like `Given I have product with "<url>"`, there needs to be some way to modify steps at runtime (before actual scenario execution).

**Comment by spolischook** [comment]
run all tests in parallel on one instance? any way it seems to be a crazy random fail idea.

**Comment by oleg-andreyev** [comment]
When we had one instance there were problems with random failures, so we've hooked into behat process and replacing "special" placeholder with unique value and we didn't had data uniqueness issue since.

P.S. we no longer run our 4k scenarios on single instance
