### ISSUE TITLE
Bdd reversed engine to generate Real pages demostration

### ISSUE THREAD

**Issue by kendoctor** [Behat/Behat#674]
This functionality I'm imagining to be real.

When I finish all feature definitions without really implementing application functionality ,
I can get a Demo Application.

According features definitions, reversed engine will build a demo project with all pages needed.
I can check all functionalities via browsing these pages.

If anyone has interest with this project , leave me a message? :)

**Comment by everzet** [comment]
In order to automate implementation from the features, your features must describe solutions. And even though it is possible, it is not the way of Behat (Behaviour Driven Development).

In Behaviour Driven Development you describe problems, so that developers can come up with right solutions. You do not describe how you would solve particular problem, you just discuss what this problem is about.

What you want to do is probably possible to certain extent, but goes against what Behat as a core is. I'd advise you pursue custom extension, so people can join you in your way of using tool. But that's not what Behat was built for, nor it is something that I see in the core of the tool.
