### ISSUE TITLE
Very slow filling an input with Mink/Selenium/PhantomJS

### ISSUE THREAD

**Issue by KuenzelIT** [Behat/Behat#712]
Hey,
I'm very new to Behat/Mink/PhantomJS and overall BDD. I just got it all working with PhantomJS to test my websites with javascript.

Everything is working fine so far, but its painly SLOW. My test only fetches the login-page and fills the username and password fields, and does nothing else. This test already takes 40 seconds to finish.

Does anyone know, what the issue could be? Don't tell me this is the normal testing time? :)

I'm running the phantomjs webdriver (phantomjs --webdriver=8643) and am using it with Behat/Mink/Selenium. Please tell me of you need any other information (I'm quite confused right now).

Thanks!

**Comment by jakzal** [comment]
Tools you use (phantomjs/selenium/other similar) ARE SLOW, and will always be. That's their nature. It's not something anyone can fix. This is a Behat repo by the way. Your issue is more related to Mink.

If you want quick tests do not go through the user interface, but exercise your code directly (then, obviously have few integration or smoke tests going through the whole thing).

**Comment by stof** [comment]
CLosing because this is indeed not a Behat issue. Behat itself is not slow (the WebDriver stack for Mink is because of how WebDriver works)

**Comment by everzet** [comment]
You could probably make it a bit faster, but not by much.

As Jakub said, going through UI in your tests is your personal choice, not something BDD or Behat dictates. And going through UI will always be slow, because instead of simply exercising code directly you go through the entire app + phantomjs stack.

I'm closing this issue as it's completely unrelated to Behat.

**Comment by stof** [comment]
And going through the UI with WebDriver is even slower than using an headless driver for Mink (BrowserKit, Goutte or Zombie)

**Comment by KuenzelIT** [comment]
Alright, I'm going to ask at the MInk-repo then.

@stof As i said, I'm still quite confused with all of this. Isn't PhantomJS also headless? What am I not getting in your last comment?

I want to go through the UI to make it as "real" as possible. And i need Javascript for this. Unfortunately Zombie didn't work on my machine, so I switched to PhantomJS.
