### ISSUE TITLE
Allow to specify a report filename for the JUnit formatter

### ISSUE THREAD

**Issue by jakzal** [Behat/Behat#747]
I need to specify a report file name from the command line. Currently the `--output` option only accepts a directory name, and the file name is generated from a suite name.

When trying to run features in parallel, or for multiple profiles, the reports will be overwritten by consecutive runs.

**Comment by stof** [comment]
The issue is that an exercise containing multiple suites will need to generate multiple files. the JUnit format does not allow to output the results of several suites in the same file in a meaningful way AFAIK (if I'm wrong, a PR improving the JUnit formatter is of course welcome).

If you are running features in parallel, the best option is probably to use a different folder each time

**Comment by jakzal** [comment]
Indeed. This should work equally well.
