### ISSUE TITLE
How do I upgrade 2.x to 3.x?

### ISSUE THREAD

**Issue by MacDada** [Behat/Behat#799]
Hi,

I have projects that use `Behat` `v.2.5.5`. How do I upgrade to 3.x (v.3.0.15)?

I looked into https://github.com/Behat/Behat/blob/v3.0.15/CHANGES.md#300beta1--2013-08-13
It does tell me that u made some major changes (like `New suite-centric architecture`) but it doesn't tell me how do I respond to those changes.

Any document/help on that? Or am I supposed to look at the diff of changes and come up with the test fixes myself?

**Comment by jakzal** [comment]
There's no migration document as far as I know. As long as you didn't rely on mink too much, the migration isnt't hard. 

On a high level you'll need to:
* update the configuration file (suites mentioned by you)
* update your contexts to implement the Context interface instead of extending the base context class
* instead of using sub-contexts, configure all of them in behat.yml (all contexts are equal now!)
* write a cookbook on migration ;)

I've done this in past and it wasn't really hard. However, my contexts were decoupled from mink and I didn't have too many dependencies between contexts.

I'm happy to help you with specific issues that might arise as you proceed with the migration.

**Comment by djdevin** [comment]
We just did a successful migration from Behat 2 to 3, it was alright.

Besides the above, if you used chained steps (`new Given("I do another step")`) in your contexts those no longer work, you have to make direct calls to the steps.

We didn't have any to update any .feature files, we used DrupalExtension and Mink.

**Comment by everzet** [comment]
I think upgrade hurdle was always overrated. We could do better job at docs, though. @djdevin care to contribute a cookbook to https://github.com/behat/docs ? :)
