### ISSUE TITLE
JUnit Ouput - Is it possible to add time attribute ?

### ISSUE THREAD

**Issue by AzKhEM** [Behat/Behat#820]
Hi,

First, thanks for your job.

I've test the Junit XML output for Behat 3, it work's, but it miss the optional time attribute in seconds (`<xs:attribute name="time" type="xs:string" use="optional"/>`) on testcase element.

Is it possible to add it?

Current output:

``` xml
<testcase name="1.Affichage du site" status="passed"></testcase>
```

Desired output:

``` xml
<testcase name="1.Affichage du site" status="passed" time="2"></testcase>
```

**Comment by higrow** [comment]
this would be a great addition for me too.

I can see why the optional attributes are not implemented right now, but would i be a possibility to add a hook to the Output/Node Generation? This would give developers a way to add optional attributes if they need any without cluttering the code too much. 

thanks anyway for your work on this.

**Comment by everzet** [comment]
If that attribute wouldn't confuse existing implementations of JUnit (Jenkins and such), I'm all for it.

**Comment by vmwiz** [comment]
I would definitely love to see this implemented

**Comment by davidsteinsland** [comment]
@everzet I would actually improve those CIs, especially CircleCI which has an option to load balance tests between containers (automatically), by looking at the `time` property.

Here's how it looks in CircleCI's test summary:
![screen shot 2016-09-14 at 12 54 46](https://cloud.githubusercontent.com/assets/125661/18509739/7732f0ce-7a7a-11e6-9592-3c6d5a14b090.png)

**Comment by djdevin** [comment]
We really need this to pinpoint long running tests/performance issues.

Thought this was easy by just adding "time" and "timestamp" in JUnitScenarioPrinter.php but I'm not sure where we would pull the duration from.

**Comment by higrow** [comment]
I implemented a initial version of this in my fork. https://github.com/higrow/Behat/commit/eabe3346303034ba9426b84b4791a660abfaf2b5

if anyone can verify the approach i'm happy to add tests, clean up and make a pull request. 

I'm unsure how to get the tests passing though because the junit format tests verify the equality of the generated file with the content specified in the junit_format.feature
Because the execution time varies i'd have to either stub the duration somehow or change the check to only verify the format, not the exact content. Any preference there?

**Comment by guillaumeray** [comment]
It would be great to have an easy and clean way to do it, with a behat extension for example

**Comment by paulholden** [comment]
Seems the _time_ attribute was written to JUnit output in [Behat 2.5](https://github.com/Behat/Behat/blob/2.5/src/Behat/Behat/Formatter/JUnitFormatter.php#L261-L295) - since upgrading to Behat 3.1 it's noticeable that Jenkins CI has stopped gathering test duration statistics, as the _time_ attribute is missing from the XML... would be great to get this back!

**Comment by spolischook** [comment]
@everzet changes by https://github.com/higrow/Behat/commit/eabe3346303034ba9426b84b4791a660abfaf2b5 as clear as possible. Can I add behat scenarios for this feature?

**Comment by spolischook** [comment]
@guillaumeray it would be nice to have a CLI Controller in your extension

**Comment by spolischook** [comment]
@higrow @everzet can you look at PR https://github.com/Behat/Behat/pull/1083

**Comment by spolischook** [comment]
@wouterj please, take a look https://github.com/Behat/Behat/pull/1083

**Comment by djdevin** [comment]
#1083 fixes this. confirmed working in behat 3.5+
