### ISSUE TITLE
Marking a scenario as failed in @afterScenario

### ISSUE THREAD

**Issue by nicrodgers** [Behat/Behat#842]
Is it possible to mark a scenario as failed in an afterScenario function?

**Comment by everzet** [comment]
Nope.

**Comment by emulgeator** [comment]
@everzet Is there a way to do this somehow then? 
Right now in the afterScenario we are checking if the called application had any errors, warnings or notices and if it had we throw an Exception. The problem is that though cli output contains this the test itself is not failed.

**Comment by spolischook** [comment]
@emulgeator you can create step to check this

**Comment by emulgeator** [comment]
@spolischook But every step I have should check this at the end, as clearly no errors should be trigger between normal circumstances. That means if I have 300 scenarios I have to add 300 steps which is far from optimal

**Comment by weitzman** [comment]
FWIW I have the same need. Adding 300 steps (see prior post) is a poor workaround.

**Comment by danepowell** [comment]
I'm also trying to figure out how to catch any errors/warnings/notices that occur during a scenario and fail the scenario. I can't think of any reasonable way to do this other than via AfterScenario, which unfortunately doesn't actually fail the scenario. Steps doesn't feel like a reasonable workaround at all.

**Comment by mikemadison13** [comment]
This is happening elsewhere for me as well, where another package is throwing a fatal (occasionally) during a behat build, and behat doesn't seem to recognize that the fatal should be treated as a failure.

**Comment by shouze** [comment]
I also have the case, would be nice to add something that could at least specify a result code from the AfterScenario hook to override the current scenario result code, no?

**Comment by benjamind01** [comment]
Is there any news about this issue please? It seems significant to me that an AfterScenario hook has the possibility to make fail the scenario.

**Comment by thomasvisma** [comment]
We have a similar scenario, we use Behat for flow-testing where we mock external web services.
In a hook after each scenario we would want to assert that all expected requests have been made, and if not, fail the feature.

Having to specify an additional step in every scenario seems to be a very error-prone approach.
Also we write scenarios in more of a user story/non technical way, we would need to add an extra step just for technical purposes which goes against that.

I'm wondering how people solved issues like this.

**Comment by stof** [comment]
This would totally break reported like the pretty reporter if you can change the outcome of a scenario after that scenario has ended, because it could have already been reported as successful (depending on the order of listeners between your mock and the reporter)

**Comment by acoulton** [comment]
Luckily (maybe) I got a notification too :) I think things might have moved on since this was first filed, because hooks definitely now fail the build (e.g. make it exit with an exit code 1) - but as @stof says making them change the result of an actual scenario would be challenging due to the sequence of listeners.

As it stands, the output for both --pretty and --progress **does** show the hook failures, but it's not always easy to see what scenario they were from, and the summary at the end (e.g. "3 scenarios (3 passed)") doesn't tell you there were failing hooks.

If you want to open a new issue - or better yet, a pull request - to enhance the formatter output to make it easier to see when / where hooks have failed that could definitely be useful.

On your broader question, my opinion would be that: 
* if the assertions are actually part of the business requirements (e.g. the expected request is "and the destination bank should have received a transfer notification for £15.00") then they should be part of the scenario, even if that is repetitive across lots of scenarios.
* if they are sanity checks for developers (e.g. "no errors were reported during the scenario") then actually they probably shouldn't fail the scenario itself - because all the business/user-defined requirements were satisfied. So an assertion in an AfterScenario hook might be valid, and it should be easy for developers to see which scenario they were related to.
