### ISSUE TITLE
Behat 3 consuming lot of memory for results.

### ISSUE THREAD

**Issue by rajeshtaneja** [Behat/Behat#848]
While transition from Behat 2.5.5 to behat 3.1.0-RC2 it was realised that memory used to save results is huge compared to what was in Behat 2.5.5

Following are the observations with https://github.com/rajeshtaneja/MinkExtension-example.git
- 12 steps : 17.78Mb
- 72 steps: 18.73 Mb (Multiple features)
- 752 Steps : 27.94Mb (Single big feature)

We have around 45000 steps and with above results it will use around 550Mb. which is quite significant.

## Steps to reproduce:
> git clone https://github.com/rajeshtaneja/MinkExtension-example.git
cd MinkExtension-example
curl http://getcomposer.org/installer | php
php composer.phar install
#### Run Behat for 4 steps
git checkout smallfeature
bin/behat
##### Run behat with steps
git checkout bigfeature
bin/behat
#### Run behat with multiple features
git checkout multiplefeature
bin/behat

**Comment by stof** [comment]
Well, having a single huge feature file will indeed use more memory than several small files, as Behat loads features one by one, but it has to load the whole feature. You should really split your scenarios into separate feature files. Having 45000 steps in the feature file looks insane.

Regarding the comparison with Behat 2.5.5, I only see a set of numbers, not 2, so it does not allow us to see the difference. And please also try it on the stable 3.0.15 version. In my experience, Behat 3 uses less memory than Behat 2, not more. So it could either be an edge case due to the huge files, or a regression in 3.1

**Comment by everzet** [comment]
I second @stof advice. Having a feature with 752 steps sounds crazy to me, 45k is plane insane. You are basically telling us that your features are unreadable to humans, yet you invest into writing and automating them in human-readable language.

My suggestion would be either to invest heavily in humanising your features by splitting them into much smaller, cohesive functionality slices OR to move to a proper end-to-end testing framework and stop pretending you do BDD.

**Comment by rajeshtaneja** [comment]
Thanks for the quick response @stof and @everzet 

I did a basic testing with Behat 3.0.5 and it seems memory usage is within limits. There is no extra memory used after every step. I will confirm this after running few test cases. 

As per large Feature file, that was just a quick modification to existing code, to see what's causing the problem. Also, it is quite a valid case to have lot of steps in a feature file. Consider a feature file with 2 **Scenario outline** with around 35 steps each and 10 **Examples** . Which is quite readable and total steps will be 2 x 35 x 10=700.

I will add more information on this and try find the cause of issue for 3.1.x 

FYI: Try dump memory usage after every step in 3.1.0-RC2 and you should observe incremental memory usage, which is not case in 2.5.5 or 3.0.5.

Thanks.

**Comment by rajeshtaneja** [comment]
Output buffer is not closing if buffer is empty which is nested for each call.
https://github.com/Behat/Behat/pull/852

**Comment by jakubzapletal** [comment]
Hi @rajeshtaneja, I understand that you're trying to solve a technical problem there but @everzet is right about your feature. 

There is a lot of what could be said and I'll try to say few simple tips:
a) The optimal number of steps for a scenario is 3 (given, when, then) so 12-times more can not be the best approach. Your example looks like a sequence of commands instead of revealing feature behaviour. I think it must be hard to find key steps there. Try to focus what is important for the feature.
b) Acceptance tests should cover only crucial parts of your application. I believe you could decrease an amount of examples on 1-2 and the rest of edge cases could go to lower testing layers (unit tests).

Although making the testing tool faster is one option, a focus on proper features would be more efficient for now and the future. For example: 2 scenarios with 7 steps per each and 2 examples would mean 2 * 7 * 2 = 28, that would be an improvement of performance by 96%.

**Comment by rajeshtaneja** [comment]
@jakubzapletal, I do agree what @everzet is saying. As said before the test case provided is just a **quick copy/paste** to show that there is a problem with memory consumption in 3.1.0-RC2 and not just with big feature file but with small-multiple feature files as well.

Probably my approach of defining the problem was not correct. I do agree with @everzet and @stof about the limited steps in feature file and that is one thing on our todo list to fix.

I will appreciate if @stof or @everzet can look at the the  https://github.com/rajeshtaneja/Behat/commit/4c6309b43c45205c97d2abfc39cd0879f0588c75 . The problem is that ob_get_length() should be checked for false and on 0 (zero) it should clean and close the buffer.

The problem was introduced by https://github.com/Behat/Behat/commit/97b006c538af425ea0ec0d10d962a2040278a2af

**Comment by stof** [comment]
@rajeshtaneja please open a pull request with your fix

**Comment by stof** [comment]
btw, a better fix might be to rely on ``ob_get_level()``

**Comment by rajeshtaneja** [comment]
Thanks @stof 

As output buffer is stackable, could it be possible that there is a open buffer before  [startErrorAndOutputBuffering()](https://github.com/Behat/Behat/blob/master/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php#L127) is called ? 
Rather then relying on ob_get_level() or ob_get_length() it would be nice to just keep track if the buffer was successfully open and if yes the close it.
Patch implementing it:
https://github.com/rajeshtaneja/Behat/commit/d68cfc0c3f50ce169f1421575d95dae6da8104da
