### ISSUE TITLE
problem with Behat 3 ( I should be on "https://something1.domain.example/hello/" )

### ISSUE THREAD

**Issue by rebajz** [Behat/Behat#853]
I have this scenario
@javascript
  Scenario: bla bla
    When I click on the element with css selector ".navbar-brand>img"
    When wait 5 seconds
    Then I should be on "https://something1.domain.example/hello/"

CSS selector .navbar-brand have link to https://something2.domain.example/hello/
After test i have this step as OK status, because behat doing only collation in /hello/ - this is same, domain is same, but something1 (in scenario) is different (something in url).

Can somebody help me, write new working function?

**Comment by jakzal** [comment]
By the looks of your scenario you used Mink with the MinkExtension for Behat, so your problem is not really related to this repository. 

Anyway, you'd be probably better off asking on stackoverflow.com which is specially designed for Q/As. Github repositories are mostly monitored by people intersted in tool's development.

**Comment by rebajz** [comment]
thanks, ok, understand

But this working for me:
/**
     *
     * @Then /^I check url "([^"]*)" i should be on$/
    */
    public function checkURLIShouldBeOn($field){
        $session = $this->getSession();
        $domain = $session->getCurrentUrl();

        if (strpos($domain,$field) !== false){
            echo "url are same";
        }else{
            throw new \Exception('Im not on url i wanted to be. Im on url ' . $domain);
        }
    }
