### ISSUE TITLE
[3.1.0] PHAR file built with box2 seems broken

### ISSUE THREAD

**Issue by 1ma** [Behat/Behat#892]
Steps to reproduce:

```sh
~$ wget https://github.com/Behat/Behat/archive/v3.1.0.tar.gz
~$ tar zxf v3.1.0.tar.gz
~$ cd Behat-3.1.0
~/Behat-3.1.0$ curl -LSs https://box-project.github.io/box2/installer.php | php
~/Behat-3.1.0$ composer install --no-dev -q
~/Behat-3.1.0$ php box.phar build
~/Behat-3.1.0$ php behat.phar
PHP Fatal error:  Cannot redeclare composerRequire3b789041321d3943276dff3aa58095fd() (previously declared in /home/marcel/Behat-3.1.0/vendor/composer/autoload_real.php:63) in phar:///home/marcel/Behat-3.1.0/behat.phar/vendor/composer/autoload_real.php on line 70
```

Changing v3.1.0.tar.gz for another stable release like 3.0.15 works fine.

**Comment by stof** [comment]
the issue is that you are loading the local composer autoloading when running behat, and this is the same file than the one used when building the phar, so the random string added in the function name is the same in the phar and in your local project.
If you run ``composer dump-autoload`` again in your local behat project, it will use a different random string, which will not conflict with the phar.

The issue happens only because you use the phar to run behat on the source code used to generate the phar itself.

**Comment by 1ma** [comment]
You are right, stof :+1: Thank you.
