### ISSUE TITLE
Does Behat generate Code Coverage?

### ISSUE THREAD

**Issue by fabiofabbrucci** [Behat/Behat#92]
Hi
i asking sorry in case I didnt see the options that enable this feature.
I case its not my mistake can behat show codecoverage, in clover format?
Is there a way to integrate behat with phpunit?

Thank you. And have a nice day.

**Comment by gggeek** [comment]
I will try to refrain from the test-purist vs. test-pragmatist approach discussion, but I definitely see some value in being able to get code coverage out of behat tests:
- using only 1 testing framework instead of 2 or 3 has a lot of value, esp. when you have to teach all team members how to write tests, or when the set of configs to run your tests against is complex enough that you have to write your test-executor-framework on top of the chosen test-framework
- even if believing strongly in code coverage is bad, looking at the reports as ballpark-figures can be enlightening: finding scenarios you forgot to write, changes between spec time and implementation time leading to huge chunks of dead code etc...
- sometimes you might end up in a project where only behaviour tests have been written and not unit tests, for any reason outside of your control (lack of resources, anyone?)
- when developing and testing a REST API, the diving line between unit test and functional test gets much thinner and you do not have selenium acting as a middleman. Sending to the API tested the magical cookie which starts xdebug code coverage and retrieving it for treatment is not so hard

I short, I do not advocate adding it by default in behat, but I vote plus one for documenting how it is possible, or having a behat extension making it easier.

**Comment by SvenBrunk** [comment]
Exactly. For that I would even like to have it down to line coverage (or more path coverage, so I know what logical paths were taken and which not)

**Comment by stof** [comment]
@gggeek there is already an extension doing this: https://packagist.org/packages/vipsoft/code-coverage-extension

**Comment by gggeek** [comment]
@stof thanks. It is not very clear from the docs if that only works for Sf, though, or if its more generic
