### ISSUE TITLE
Scenarios list file

### ISSUE THREAD

**Issue by davidsteinsland** [Behat/Behat#948]
Would be help to add support for listing other `.scenarios` files within a `.scenarios` file.

Usage example:
When you have split your tests into two (or more) `.scenarios` file, and you want to have one "master" file which just includes the others.

master.scenarios
```
a.scenarios
b.scenarios
```

a.scenarios:
```
a.feature
b.feature
```

**Comment by spolischook** [comment]
maybe you can use suites for this purpose?

**Comment by davidsteinsland** [comment]
Suites works well if the different tests had been in separate paths, but not all of them are. This is part of our acceptance testing across several applications, where the CI runs `a.scenarios` in one container and `b.scenarios` in another container (to parallelize the builds).

On our development machines, we want to run `master.scenarios` to run all of them easily.

We have created extensions that creates database fixtures for us (we can run one feature and "save" the SQL queries to a file, which can be imported in another feature). 
This results in that features must be executed in a given order, hence the scenarios files..

Also, because we are testing across several applications (with different base URLs), we have an extension that automatically updates Mink's `base_url` parameter for each test (based on the directory they live in).

Example:
```
app1/
  - a.feature
  - b.feature
app2/
  - a.feature
  - b.feature
```

Because we use the "app1" and "app2" directories to identify the base URL requirement, we cannot move the features around in paths such as "suite1/" and "suite2/". 

Conclusion: I don't think we can solve this using Suites.

**Comment by everzet** [comment]
This sounds like a very deliberate setup focused around parallelisation. If you already have automated scripts (you probably should) that generate your `*.scenarios` files, why these scripts can't generate flat `*.scenarios` files instead of relying on this inexistent hierarchy.

On our side, `*.scenarios` was a feature intended to simplify sharing of particular scenario subset between individual team members. What you are doing here obviously doesn't match that intention and I don't really want to overcomplicate the feature for a narrow use case.
