### ISSUE TITLE
Date Time Testing Handling?

### ISSUE THREAD

**Issue by juanmrad** [Behat/Behat#967]
I have to do testing, and I've been having issue when I do testing at certain hours of the day ( after 6pm. ) or certain days ( weekends ) is there a way to set a local time when the testing is running to avoid this type of issues?

**Comment by avant1** [comment]
As I know PHP itself relies on system time, so one possible thing to do is to change system time to wanted date.
But it is a bad approach since it may lead to serious problems with other services that rely on system time.

More reliable and accurate way is to avoid direct usage of build-in PHP functionality (like `time()` or `new \DateTime()`) to detect current time but wrap all such calls in a service (or function) and use this wrapper when you need get current date.
Inside that service depending on some conditions in test environment you can return custom time if it was defined, or just current time if scenario does not depend on time.

Simple example:
```php
class Clock
{
    public function getCurrentTime()
    {
        $pathToTimeFile = 'some/path/to/current-time.txt';
        if (file_exists($pathToTimeFile)) {
            return new \DateTime(file_get_contents($pathToTimeFile));
        }

        return new \DateTime();
    }
}
```
And when you want to change current date you just put wanted date to that file (or remove that file if using current time is fine for your scenario).
