### ISSUE TITLE
Handle php fatal error

### ISSUE THREAD

**Issue by spolischook** [Behat/Behat#984]
It would be great to catch all exceptions not only SearchException to have to know what feature was failed, especially when progress formarter is used

**Comment by stof** [comment]
which catch are you talking about ?

**Comment by spolischook** [comment]
In RuntimeStepTester, when some users code runs it can be throw any kind of errors.
https://github.com/Behat/Behat/blob/a998d45dca71340d5dd79b60fe1b6f7c70ff08fe/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php#L73
I think it's affect all behat users, cause some times error was happen and I can't recognize what feature was produce it.

**Comment by everzet** [comment]
All step definitions go through [`CallCenter::makeCall`](https://github.com/Behat/Behat/blob/master/src/Behat/Testwork/Call/CallCenter.php#L86-L102), which catches all exceptions. The catch you're referring to is only there to catch exceptions from inside [definitions search routine](https://github.com/Behat/Behat/blob/a998d45dca71340d5dd79b60fe1b6f7c70ff08fe/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php#L72).

**Comment by spolischook** [comment]
This is not resolve my issue. When I use progress loader I can't recognize what feature was produce the exception.

**Comment by everzet** [comment]
You didn't describe issue - you asked for a feature. I pointed that feature is already implemented as part of Behat core, granting closure of this particular ticket.

I'm afraid we can't help you much until you [describe your issue clearly](https://github.com/Behat/Behat/blob/master/CONTRIBUTING.md#submitting-an-issue). I'd use separate ticket for that. Please make sure you provide enough context so that we can actually help you debug the issue instead of guessing what's wrong.
